### ISSUE TITLE
Множественный редирект

### ISSUE THREAD

**Issue by anmaslov** [rivetweb/rodzeta.redirect#21]
Если в переменных сервера не задано в разделе HTTP Headers Information переменной HTTPS, а в настройках модуля стоит переадресация с http на https - происходит зацикливание.

https://github.com/rivetweb/rodzeta.redirect/blob/master/include.php#L81

Переменная `$protocol` всегда возвращает `http`

Решается добавлением в .htaccess
```
<IfModule mod_env.c>
   SetEnv HTTPS on
</IfModule>
```

Как пояснил хостинг провайдер:
> Дело в том, что переменная HTTPS отсутствует по умолчанию при связке nginx+apache, так как 443 слушает Nginx, то у apache вообще нет модуля mod_ssl.

**Comment by rivetweb** [comment]
все верно - для переадресации с https на http сервер должен быть корректно настроен.
